import localFont from "next/font/local";
import "./globals.css";
import Styles from "./layout.module.css"
import Img from "./public/logo.png";
import Image from "next/image"; 
import Link from "next/link"; 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<html lang="es">
      <body>
        <header className={Styles.header}>
          <div className={Styles.logo}>
          <Image 
          src={Img}
          width={50}
          height={50}
          alt="Imagen logo"
        />
            <h1 className={Styles.h1}>EventoGo</h1>
          </div>
          <nav className={Styles.nav}>
          <ul className={Styles.ul}>
              <li><Link href="/Home" className={Styles.a}>Home</Link></li>
              <li><Link href="/Contacto" className={Styles.a}>Contacto</Link></li> 
              <li><Link href="/perfil" className={Styles.a}>UsuarioXXX</Link></li>
              <li><Link href="/logout" className={Styles.a}>Cerrar sesión</Link></li>
            </ul>
          </nav>
        </header>

        <main className={Styles.main}>
          {children}
        </main>

        <footer className={Styles.footer}>
      <div className={Styles.container}>
        <div className={Styles.separacion}>
          <ul className={Styles.links}>
            <li><p className={Styles.textfooter}>Términos de Servicio</p></li>
            <li><p className={Styles.textfooter}>Política de Privacidad</p></li>
            <li><Link href="/Contacto" className={Styles.link}>Contacto</Link></li>
          </ul>
          <div>
            <h2 className={Styles.textfooter}>Información</h2>
            <p className={Styles.textfooter}>
              <strong>Email:</strong> contacto@eventos.com<br />
              <strong>Teléfono:</strong> +54 9 1234 5678
            </p>
          </div>
          <div>
            <h2 className={Styles.textfooter}>Síguenos en Redes Sociales</h2>
            <ul className={Styles.socialMedia}>
              <li><a href="https://facebook.com" className={Styles.link}>Facebook</a></li>
              <li><a href="https://twitter.com" className={Styles.link}>Twitter</a></li>
              <li><a href="https://instagram.com" className={Styles.link}>Instagram</a></li>
            </ul>
          </div>
        </div>
        <p>© 2024 EventoGo. Todos los derechos reservados.</p>
      </div>
    </footer>
      </body>
    </html>
  );
}



